{ "display_name":"Conviva",
  "description": "SignalFx Smart Agent monitor for ingesting Real-Time/Live Conviva metrics",
  "project_url": "https://github.com/signalfx/integrations/tree/master/conviva",
  "code": "https://github.com/signalfx/signalfx-agent/tree/master/internal/monitors/conviva",
  "featured": false,
  "logo_large": "/images/repos/conviva/img/integration_conviva@2x.png",
  "logo_small": "/images/repos/conviva/img/integration_conviva.png",
  "data_signature": "metric_source:\"conviva\"",
  "in_app_categories": ["servicesMonitored"]
}
