{ "display_name":"Consul",
  "description": "Monitor Consul using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-consul",
  "code": "https://github.com/signalfx/collectd-consul",
  "featured": false,
  "logo_small": "/images/repos/collectd-consul/img/integrations_consul.png",
  "logo_large": "/images/repos/collectd-consul/img/integrations_consul%402x.png",
  "data_signature": "plugin:\"consul\"",
  "in_app_categories": ["servicesMonitored"]
}
