{ "display_name":"SignalFx POPS (Point Of Presence Service)",
  "description": "Aggregate metrics with different tokens from collectd, json, or protobuf and forward them to SignalFx.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/pops",
  "code": "https://github.com/signalfx/pops",
  "featured": false,
}
