{ "display_name":"Elasticsearch",
  "description": "Monitor Elasticsearch using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-elasticsearch",
  "code": "https://github.com/signalfx/collectd-elasticsearch",
  "featured": true,
  "logo_small": "/images/repos/collectd-elasticsearch/img/integrations_elasticsearch.png",
  "logo_large": "/images/repos/collectd-elasticsearch/img/integrations_elasticsearch%402x.png",
  "data_signature": "plugin:\"elasticsearch\"",  
  "in_app_categories": ["servicesMonitored"]
}
