{"display_name":"Kong",
 "description": "Monitor Kong API Gateway.",
 "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-kong",
 "code": "https://github.com/signalfx/collectd-kong",
 "featured": false,
 "logo_small": "/images/repos/collectd-kong/img/integrations_kong.png",
 "logo_large": "/images/repos/collectd-kong/img/integrations_kong%402x.png",
 "data_signature": "plugin:\"kong\"",
 "in_app_categories": ["servicesMonitored"]}
