{ "display_name":"Jenkins",
  "description": "Monitor Jenkins using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-jenkins",
  "code": "https://github.com/signalfx/collectd-jenkins",
  "featured": false,
  "logo_small": "/images/repos/collectd-jenkins/img/integrations_jenkins.png",
  "logo_large": "/images/repos/collectd-jenkins/img/integrations_jenkins%402x.png",
  "data_signature": "plugin:\"jenkins\"",
  "in_app_categories": ["servicesMonitored"]
}
