{ "display_name":"AWS Kinesis",
  "description": "SignalFx's integration with AWS Kinesis.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/aws-kinesis",
  "code": "https://aws.amazon.com/kinesis/",
  "featured": false,
  "logo_large": "integration_awskinesisstreams%402x.png",
  "logo_small": "integration_awskinesisstreams.png",
  "data_signature": "namespace:\"AWS/Kinesis\"",
  "in_app_categories": ["AWSservicesMonitored"]
}
