{ "display_name":"Cisco IOS XR Integration",
  "description": "Cisco IOS XR Integration for SignalFx",
  "project_url": "https://github.com/signalfx/integrations/tree/master/logstash-ciscoxr",
  "code": "https://github.com/cisco/bigmuddy-network-telemetry-stacks",
  "featured": true,
  "logo_small": "/images/repos/logstash-ciscoxr/img/integrations_ciscoiosxr.png",
  "logo_large": "/images/repos/logstash-ciscoxr/img/integrations_ciscoiosxr%402x.png"
}
