  config:
    - host: 192.168.1.60
      username: administrator@vsphere.local
      password: Abcd123$
      Name: VCenter4
      IngestToken: <YOUR_SIGNALFX_API_TOKEN>
      IngestEndpoint: 'https://ingest.us0.signalfx.com'
      IngestTimeout: 20
      MORSyncInterval: 300
      MORSyncTimeout: 600
      MetricSyncInterval: 300
      MetricSyncTimeout: 600
      IncludeMetrics:
        host:
          - mem.swapused.average
        cluster:
          - mem.usage.average
      ExcludeMetrics:
        datacenter:
          - cpu.usage.average
        vm:
          - mem.usage.average
      Dimensions:
        dimension_key: "dimension_value"
        dimension_key1: "dimension_value1"
