{ "display_name":"vSphere",
  "description": "Monitor vSphere using the SignalFx-vSphere application",
  "project_url": "https://github.com/signalfx/integrations/tree/master/vmware-vsphere",
  "code": "https://github.com/signalfx/signalfx-vsphere",
  "featured": false,
  "logo_small": "/images/repos/vmware-vsphere/img/integrations_vsphere.png",
  "logo_large": "/images/repos/vmware-vsphere/img/integrations_vsphere%402x.png",
  "data_signature": "metric_source:\"vsphere\"",
  "in_app_categories": ["servicesMonitored"]
}
