{ "display_name":"IOStat",
  "description": "Monitor IOStat metrics",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-iostat",
  "code": "https://github.com/signalfx/iostat-collectd-python",
  "featured": false,
  "logo_small": "/images/repos/collectd-docker/img/integrations_iostat.png",
  "logo_large": "/images/repos/collectd-docker/img/integrations_iostat%402x.png"
}
