{ "display_name":"MongoDB",
  "description": "Monitor MongoDB using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/collectd-mongodb",
  "code": "https://github.com/signalfx/collectd-mongodb",
  "featured": true,
  "logo_small": "/images/repos/collectd-mongodb/img/integrations_mongodb.png",
  "logo_large": "/images/repos/collectd-mongodb/img/integrations_mongodb%402x.png",
  "data_signature": "plugin:\"mongo\"",
  "in_app_categories": ["servicesMonitored"]
}
