{ "display_name":"StatsD.NET",
  "description": "SignalFx Integration for Windows StatsD.NET",
  "project_url": "https://github.com/signalfx/integrations/tree/master/win-statsd.net",
  "code": "https://github.com/signalfx/signalfx-statsd.net-plugin",
  "featured": false,
  "logo_small": "/images/repos/win-statsd.net/img/integrations_windows.png",
  "logo_large": "/images/repos/win-statsd.net/img/integrations_windows%402x.png",
  "in_app_categories": ["servicesMonitored"]
}
