{ "display_name":"Google Cloud Platform",
   "description": "SignalFx's integration with Google Cloud Platform's StackDriver.",
   "project_url": "https://github.com/signalfx/integrations/tree/master/gcp",
   "code": "https://cloud.google.com/stackdriver/",
   "featured": false,
   "logo_large": "integration_gcp.png",
   "logo_small": "integration_gcp.png",
   "in_app_categories": ["essential", "servicesMonitored", "GCPServicesMonitored"]
 }
