{ "display_name": "SignalFx Smart Gateway",
  "description": "SignalFx's Smart Gateway for Microservices APM and NoSample™️",
  "project_url": "https://docs.signalfx.com/en/latest/apm/apm-overview/index.html",
  "featured": true,
  "sort_order": 0,
  "logo_large": "integration_smartgateway@2x.png",
  "logo_small": "integration_smartgateway.png",
  "data_signature": "sf_metric:\"gateway.processedTraces\"",
  "in_app_categories": ["essential"],
  "feature": "apm",
}
